### ISSUE TITLE
@gauravrpjain will create functions extract the different section of files: additionality, summary, project (claims), market (claims), indicator table.

### ISSUE THREAD

**Issue by alinealinealine** [alinealinealine/GPT-Pilot#3]

**Comment by alinealinealine** [comment]
@gauravrpjain separated as a single issue here instead.

**Comment by alinealinealine** [comment]
updated the code with a simple function: see details: https://github.com/alinealinealine/GPT-Pilot/commit/673d926951112b39421014b0eb1372e676b04064

@gauravrpjain I did the regular expression based on the pattern for each section according to MAS narrative. However, it might not be the case for other sectors, the function should be customized by sector. Also, further adjustment needed on identifying the table and the indicators (comparatively easier, because the table items can be identified easily with the summary_tagging.

**Comment by alinealinealine** [comment]
Use the latest splitting function (without customization by sector): the performance (successfully split the sections into additionally, project, and market sections, though some misclassifications exist) is below:

- MAS: 71% (153 projects)
- CDF: 70% (79 projects)
- FIG: 66% (151 projects)
- INR: 79% (84 projects)

**Comment by alinealinealine** [comment]
After the agreement to focus on FIG, I refined the fig subfile and the accuracy rate is about 94%. The subfile will be the template moving forward for other sectors.

**Comment by gauravrpjain** [comment]
I have completed the edits on extracting indicators and have around 99% accuracy (out of the files you were able to read). There are nine files that I either failed to read with docxtractr library, or the file doesn't have an AIMM indicator table. 

This is currently only for FIG.

**Comment by alinealinealine** [comment]
The code runs well on my end. One question @gauravrpjain , there're a lot of cell values as "DOTS Template". Should we just delete these in the final data set?

**Comment by gauravrpjain** [comment]
The DOTS Template issue should be resolved as I added code to read those older templates. 

The code runs well, but still, there are a few files that are not properly read - some identified by JP as okay docs but can't be read by the code. I will give it another look before closing the issue.

**Comment by gauravrpjain** [comment]
Did the edits to resolve indicator collection, and the code works with a decent success rate for other sectors too!
